name: Hello workflow

on:
 workflow_dispatch:
 push:
  branches: main
env:
  APP_NAME: myapp

jobs:
  hello-job:
    env:
      VERSION: 1.0
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO FROM MY FIRST WORKFLOW"
      - run: echo "APP= $APP_NAME"
      - run: echo "VERSION= $VERSION"

  new-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO FROM MY FIRST WORKFLOW"
      - run: echo "APP= $APP_NAME"
      - run: echo "VERSION= $VERSION"
