name: Hello workflow

on:
 workflow_dispatch:
env:
  APP_NAME: myapp

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HELLO FROM MY FIRST WORKFLOW"
      - run: echo "APP= $APP_NAME"
